//Code generated by Claude 4.6 Sonnet (Anthropic), accessed April 2026.
//Prompt: "Write a bare-metal C startup file for the MSPM0C1104 that implements the vector table and Reset_Handler."
//The code was reviewed and adapted by Hanseo Ryu.

#include <stdint.h>

/* Symbols defined by the linker script (mspm0c1104.ld) */
extern uint32_t _sidata;  /* start of .data initial values in FLASH */
extern uint32_t _sdata;   /* start of .data in SRAM */
extern uint32_t _edata;   /* end of .data in SRAM */
extern uint32_t _sbss;    /* start of .bss in SRAM */
extern uint32_t _ebss;    /* end of .bss in SRAM */
extern uint32_t _estack;  /* top of stack (end of SRAM) */

int main(void);

/* Default handler for unimplemented interrupts: halts execution.
   Marked weak+alias so any handler can be overridden by redefining it. */
static void default_handler(void)
{
    for (;;) {
    }
}

void Reset_Handler(void);
void NMI_Handler(void)          __attribute__((weak, alias("default_handler")));
void HardFault_Handler(void)    __attribute__((weak, alias("default_handler")));
void SVC_Handler(void)          __attribute__((weak, alias("default_handler")));
void PendSV_Handler(void)       __attribute__((weak, alias("default_handler")));
void SysTick_Handler(void)      __attribute__((weak, alias("default_handler")));
void INT_GROUP0_Handler(void)   __attribute__((weak, alias("default_handler")));
void GPIOA_IRQHandler(void)     __attribute__((weak, alias("default_handler")));
void TIMG8_IRQHandler(void)     __attribute__((weak, alias("default_handler")));
void ADC0_IRQHandler(void)      __attribute__((weak, alias("default_handler")));
void SPI0_IRQHandler(void)      __attribute__((weak, alias("default_handler")));
void UART0_IRQHandler(void)     __attribute__((weak, alias("default_handler")));
void TIMG14_IRQHandler(void)    __attribute__((weak, alias("default_handler")));
void TIMA0_IRQHandler(void)     __attribute__((weak, alias("default_handler")));
void I2C0_IRQHandler(void)      __attribute__((weak, alias("default_handler")));
void DMA_IRQHandler(void)       __attribute__((weak, alias("default_handler")));

/* Interrupt vector table — must be placed at the very start of FLASH.
   ARM Cortex-M hardware reads [0] for the initial stack pointer
   and [1] for the reset entry point on every reset.
   Peripheral IRQs start at index 16 (exception 16).
   Ref: MSPM0 C-series Microcontroller TRM, page 214. */
__attribute__((section(".isr_vector")))
void (*const vector_table[])(void) = {
    (void (*)(void))(&_estack),  /* [0]  initial stack pointer */
    Reset_Handler,               /* [1]  reset handler */
    NMI_Handler,                 /* [2]  non-maskable interrupt */
    HardFault_Handler,           /* [3]  hard fault */
    0,                           /* [4]  reserved */
    0,                           /* [5]  reserved */
    0,                           /* [6]  reserved */
    0,                           /* [7]  reserved */
    0,                           /* [8]  reserved */
    0,                           /* [9]  reserved */
    0,                           /* [10] reserved */
    SVC_Handler,                 /* [11] supervisor call */
    0,                           /* [12] reserved */
    0,                           /* [13] reserved */
    PendSV_Handler,              /* [14] pendable service call */
    SysTick_Handler,             /* [15] system tick timer */
    INT_GROUP0_Handler,          /* [16] IRQ0: INT_GROUP0 */
    GPIOA_IRQHandler,            /* [17] IRQ1: GPIO0 */
    TIMG8_IRQHandler,            /* [18] IRQ2: TIMG8 */
    0,                           /* [19] IRQ3: reserved */
    ADC0_IRQHandler,             /* [20] IRQ4: ADC0 */
    0,                           /* [21] IRQ5: reserved */
    0,                           /* [22] IRQ6: reserved */
    0,                           /* [23] IRQ7: reserved */
    0,                           /* [24] IRQ8: reserved */
    SPI0_IRQHandler,             /* [25] IRQ9: SPI0 */
    0,                           /* [26] IRQ10: reserved */
    0,                           /* [27] IRQ11: reserved */
    0,                           /* [28] IRQ12: reserved */
    0,                           /* [29] IRQ13: reserved */
    0,                           /* [30] IRQ14: reserved */
    UART0_IRQHandler,            /* [31] IRQ15: UART0 */
    TIMG14_IRQHandler,           /* [32] IRQ16: TIMG14 */
    0,                           /* [33] IRQ17: reserved */
    TIMA0_IRQHandler,            /* [34] IRQ18: TIMA0 */
    0,                           /* [35] IRQ19: reserved */
    0,                           /* [36] IRQ20: reserved */
    0,                           /* [37] IRQ21: reserved */
    0,                           /* [38] IRQ22: reserved */
    0,                           /* [39] IRQ23: reserved */
    I2C0_IRQHandler,             /* [40] IRQ24: I2C0 */
    0,                           /* [41] IRQ25: reserved */
    0,                           /* [42] IRQ26: reserved */
    0,                           /* [43] IRQ27: reserved */
    0,                           /* [44] IRQ28: reserved */
    0,                           /* [45] IRQ29: reserved */
    0,                           /* [46] IRQ30: reserved */
    DMA_IRQHandler,              /* [47] IRQ31: DMA */
};

/* Reset_Handler: sets up the C runtime environment, then calls main().
   Runs before any C code — no initialized globals or zeroed BSS yet. */
void Reset_Handler(void)
{
    /* Copy .data initial values from FLASH to SRAM */
    uint32_t *src = &_sidata;
    uint32_t *dst = &_sdata;

    while (dst < &_edata) {
        *dst++ = *src++;
    }

    /* Zero-initialize .bss (C standard requires this) */
    dst = &_sbss;
    while (dst < &_ebss) {
        *dst++ = 0u;
    }

    /* C environment is ready — jump to application */
    (void)main();

    /* Halt if main() ever returns */
    for (;;) {
    }
}
